// <auto-generated />
using System;
using LMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220617015212_AddAvatarUser")]
    partial class AddAvatarUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LMS.Data.Entity.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("ExpiresTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_time");

                    b.Property<DateTimeOffset?>("RevokedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_token_user_id");

                    b.ToTable("access_token");
                });

            modelBuilder.Entity("LMS.Data.Entity.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfTrainee")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_trainee");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text")
                        .HasColumnName("parent_code");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_course");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_course_subject_id");

                    b.ToTable("course");
                });

            modelBuilder.Entity("LMS.Data.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.ToTable("department");
                });

            modelBuilder.Entity("LMS.Data.Entity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "BasePermission",
                            Code = "PerformBaseFeatures",
                            Description = "Perform basic features such as logout, edit avatar",
                            Name = "Base Features"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Dashboard",
                            Code = "ViewDashboard",
                            Description = "View a summary of information on one display",
                            Name = "View overview of general information"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Course",
                            Code = "ViewAssignedCoursesList",
                            Description = "View assigned courses",
                            Name = "View list of assigned courses"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Course",
                            Code = "ViewAllCourses",
                            Description = "View all of courses in system",
                            Name = "View all of courses"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Course",
                            Code = "ViewDetailOfCourse",
                            Description = "View detail of course include description, outline, topics",
                            Name = "View detail of course"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Course",
                            Code = "CreateTopic",
                            Description = "Create topic in course",
                            Name = "Create topic"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Course",
                            Code = "UpdateTopic",
                            Description = "Update topic in course",
                            Name = "Update topic"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Course",
                            Code = "DeleteTopic",
                            Description = "Delete topic in course",
                            Name = "Delete topic"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Course",
                            Code = "AddLearningResource",
                            Description = "Add a new learning resource in topic",
                            Name = "Add a new learning resource"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Course",
                            Code = "DeleteLearningResource",
                            Description = "Delete the learning resource in topic",
                            Name = "Delete the learning resource"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Course",
                            Code = "ViewContentOfLearningResources",
                            Description = "View content of learning resource",
                            Name = "View content of learning resource"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Course",
                            Code = "ViewAttendeesList",
                            Description = "View list attendees in course",
                            Name = "View list attendees in course"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Course",
                            Code = "ViewSummaryOfQuizResults",
                            Description = "View summary of quiz results of students",
                            Name = "View summary of quiz results"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Course",
                            Code = "ViewDetailOfQuizResultOfStudent",
                            Description = "View detail of student’s quiz result",
                            Name = "View detail of student’s quiz result"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Course",
                            Code = "ViewSummaryOfSurveyResults",
                            Description = "View summary of survey results of students",
                            Name = "View summary of survey results"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Course",
                            Code = "ViewSummaryOfLearningProcessOfStudent",
                            Description = "View summary of student’s learning process",
                            Name = "View summary of student’s learning process"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Course",
                            Code = "ViewDetailOfLearningProcessOfStudent",
                            Description = "View detail of student’s learning process",
                            Name = "View detail of student’s learning process"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Course",
                            Code = "CreateQuiz",
                            Description = "Create quiz in topic",
                            Name = "Create quiz"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Course",
                            Code = "UpdateQuiz",
                            Description = "Update quiz in topic",
                            Name = "Update quiz"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Course",
                            Code = "DeleteQuiz",
                            Description = "Delete quiz in topic",
                            Name = "Delete quiz"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Course",
                            Code = "AttemptAndReattemptQuiz",
                            Description = "Attempt and Re-attempt quiz",
                            Name = "Attempt and Re-attempt quiz"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Course",
                            Code = "ReviewYourOwnAttempts",
                            Description = "Review your own attempts",
                            Name = "Review your own attempts"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Course",
                            Code = "PreviewQuiz",
                            Description = "Preview quiz",
                            Name = "Preview quiz"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Course",
                            Code = "AddSurveyFromTemplate",
                            Description = "Add survey from template",
                            Name = "Add survey"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Course",
                            Code = "UpdateSurvey",
                            Description = "Update survey",
                            Name = "Update survey"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Course",
                            Code = "DeleteSurvey",
                            Description = "Delete survey",
                            Name = "Delete survey"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Course",
                            Code = "DoAndEditSurvey",
                            Description = "Do and edit survey",
                            Name = "Do and edit survey"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Course",
                            Code = "PreviewSurvey",
                            Description = "Preview survey",
                            Name = "Preview survey"
                        },
                        new
                        {
                            Id = 29,
                            Category = "SurveyTemplate",
                            Code = "ViewSurveyTemplatesList",
                            Description = "View list of survey templates",
                            Name = "View list of survey templates"
                        },
                        new
                        {
                            Id = 30,
                            Category = "SurveyTemplate",
                            Code = "CreateSurveyTemplate",
                            Description = "Create a new survey template",
                            Name = "Create a new survey template"
                        },
                        new
                        {
                            Id = 31,
                            Category = "SurveyTemplate",
                            Code = "UpdateSurveyTemplate",
                            Description = "Update the survey template",
                            Name = "Update the survey template"
                        },
                        new
                        {
                            Id = 32,
                            Category = "SurveyTemplate",
                            Code = "DeleteSurveyTemplate",
                            Description = "Delete the survey template",
                            Name = "Delete the survey template"
                        },
                        new
                        {
                            Id = 33,
                            Category = "QuestionBank",
                            Code = "CreateQuestionBank",
                            Description = "Create question bank",
                            Name = "Create question bank"
                        },
                        new
                        {
                            Id = 34,
                            Category = "QuestionBank",
                            Code = "UpdateQuestionBank",
                            Description = "Update question bank",
                            Name = "Update question bank"
                        },
                        new
                        {
                            Id = 35,
                            Category = "QuestionBank",
                            Code = "DeleteQuestionBank",
                            Description = "Delete question bank",
                            Name = "Delete question bank"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Question",
                            Code = "ViewQuestionsList",
                            Description = "View list of questions in a question bank",
                            Name = "View list of questions in a question bank"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Question",
                            Code = "ViewDetailOfQuestion",
                            Description = "View detail of a question",
                            Name = "View detail of a question"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Question",
                            Code = "CreateQuestion",
                            Description = "Create question",
                            Name = "Create question"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Question",
                            Code = "UpdateQuestion",
                            Description = "Update question",
                            Name = "Update question"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Question",
                            Code = "DeleteQuestion",
                            Description = "Delete question",
                            Name = "Delete question"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Subject",
                            Code = "ViewSubjectsList",
                            Description = "View list of subjects",
                            Name = "View list of subjects"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Subject",
                            Code = "ViewDetailOfSubject",
                            Description = "View detail of subject",
                            Name = "View detail of subject"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Subject",
                            Code = "AddLearningResource",
                            Description = "Add a new learning resource",
                            Name = "Add a new learning resource"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Subject",
                            Code = "DeleteLearningResource",
                            Description = "Delete the learning resource",
                            Name = "Delete the learning resource"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Role",
                            Code = "ViewRolesList",
                            Description = "View list of roles",
                            Name = "View list of roles"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Role",
                            Code = "ViewDetailOfRole",
                            Description = "View detail of role",
                            Name = "View detail of role"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Role",
                            Code = "CreateRole",
                            Description = "Create role",
                            Name = "Create role"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Role",
                            Code = "UpdateRole",
                            Description = "Update role",
                            Name = "Update role"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Role",
                            Code = "DeleteRole",
                            Description = "Delete role",
                            Name = "Delete role"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Account",
                            Code = "ViewUsersList",
                            Description = "View list of users",
                            Name = "View list of users"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Account",
                            Code = "ViewDetailOfUser",
                            Description = "View detail of user",
                            Name = "View detail of user"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Account",
                            Code = "AssignRoleToUser",
                            Description = "Assign role to user",
                            Name = "Assign role to user"
                        });
                });

            modelBuilder.Entity("LMS.Data.Entity.PermissionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_role");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_permission_role_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permission_role_role_id");

                    b.ToTable("permission_role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 45,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 46,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 47,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 48,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 49,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 50,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 51,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 52,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 27,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("LMS.Data.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<DateTimeOffset>("ExpiresTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_time");

                    b.Property<DateTimeOffset?>("RevokedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("LMS.Data.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid")
                        .HasColumnName("delete_by");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreateTime = new DateTimeOffset(new DateTime(2022, 6, 17, 8, 52, 11, 651, DateTimeKind.Unspecified).AddTicks(2324), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreateTime = new DateTimeOffset(new DateTime(2022, 6, 17, 8, 52, 11, 654, DateTimeKind.Unspecified).AddTicks(9136), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("LMS.Data.Entity.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid")
                        .HasColumnName("delete_by");

                    b.Property<DateTimeOffset?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_user_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_user_user_id");

                    b.ToTable("role_user");
                });

            modelBuilder.Entity("LMS.Data.Entity.Subject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("LMS.Data.Entity.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(0)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_sync_log");

                    b.ToTable("sync_log");
                });

            modelBuilder.Entity("LMS.Data.Entity.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(0)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("update_by");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_topic");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_topic_course_id");

                    b.ToTable("topic");
                });

            modelBuilder.Entity("LMS.Data.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_male");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset?>("DateOfJoin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_join");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_course");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_user_course_course_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_course_user_id");

                    b.ToTable("user_course");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_department");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_user_department_department_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_department_user_id");

                    b.ToTable("user_department");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_subject");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_user_subject_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_subject_user_id");

                    b.ToTable("user_subject");
                });

            modelBuilder.Entity("LMS.Data.Entity.AccessToken", b =>
                {
                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_access_token_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.Course", b =>
                {
                    b.HasOne("LMS.Data.Entity.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_course_subject_subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LMS.Data.Entity.PermissionRole", b =>
                {
                    b.HasOne("LMS.Data.Entity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("fk_permission_role_permission_permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Data.Entity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permission_role_role_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LMS.Data.Entity.RefreshToken", b =>
                {
                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_refresh_token_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.RoleUser", b =>
                {
                    b.HasOne("LMS.Data.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_role_user_role_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_role_user_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.Topic", b =>
                {
                    b.HasOne("LMS.Data.Entity.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_topic_course_course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserCourse", b =>
                {
                    b.HasOne("LMS.Data.Entity.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_user_course_course_course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_course_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserDepartment", b =>
                {
                    b.HasOne("LMS.Data.Entity.Department", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_user_department_department_department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany("Departments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_department_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.UserSubject", b =>
                {
                    b.HasOne("LMS.Data.Entity.Subject", "Subject")
                        .WithMany("Users")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_user_subject_subject_subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Data.Entity.User", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_subject_user_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Data.Entity.Course", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("LMS.Data.Entity.Department", b =>
                {
                    b.Navigation("UserDepartments");
                });

            modelBuilder.Entity("LMS.Data.Entity.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LMS.Data.Entity.Subject", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LMS.Data.Entity.User", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Roles");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
